language: python

python:
  - "3.6"

install:
  # Install Codecov
  - pip install codecov

  - pip install -r requirements.txt

script:
  # Install
  - coverage run setup.py install

after_success:
  # Upload code coverage to Codecov
  - codecov
